### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by sunilroy007** [AbirHasan2005/Save-Group#4]
bro add cc (who leeched it) to avoid confusion and track them incase 18+ lol

**Comment by AbirHasan2005** [comment]
Already Done: https://github.com/AbirHasan2005/Save-Group/blob/7310808c1503c3bd2afac62703f3f8a3850d0117/main.py#L67

If File sent by Bot it can't get main user 😅
No Logic Found.

If you can suggest please contact at: https://t.me/DevsZone
